-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghGUCFq3BTwC/hZL+
oYn9IAoeffvK5JI2CN08DfzLoTSgCgYIKoZIzj0DAQehRANCAAQsFIFWnE6e7QcX
uCqxrYMCniqWxQ9HfE5K8MbyNi+BydklY0Kh/BElyyrjk3iTjp6EYNpII6MiS1r4
lV+fTwHX
-----END PRIVATE KEY-----